// Practice problems: the problem index, lazy problem files, points for solved problems and code drafts.
// Solved problems live in users/{uid}.dsa.solved when logged in, in this browser otherwise (moved in on login).
import { useCallback, useEffect, useState } from 'react'
import { collection, doc, getDoc, getDocs, onSnapshot, setDoc } from 'firebase/firestore'
import { db } from '../firebase'
import { readLocal, useStore, writeLocal } from '../store'
import type { Compare, Json, Signature } from './harness'
import indexJson from '../../../content/dsa-problems/index.json'

export interface ProblemMeta {
  id: string
  title: string
  topic: string
  difficulty: 'easy' | 'medium' | 'hard'
  points: number
  lc: number | null
  tags: string[]
  order: number
  /** generated by the AI pipeline (community bank or this browser) */
  ai?: boolean
}

export interface Problem extends ProblemMeta {
  statement: { hi: string; en: string }
  constraints: string[]
  hints: { hi: string[]; en: string[] }
  signature: Signature
  compare: Compare
  starter: string
  examples: { args: Json[]; expected: Json; explain?: { hi: string; en: string } }[]
  tests: { args: Json[]; expected: Json }[]
  solution: { approach: { hi: string; en: string }; cpp: string }
}

export interface Solved {
  points: number
  at: number
}

export const PROBLEMS = indexJson as ProblemMeta[]

const files = import.meta.glob(['../../../content/dsa-problems/*.json', '!../../../content/dsa-problems/index.json'], { import: 'default' }) as Record<string, () => Promise<unknown>>

export async function loadProblem(id: string): Promise<Problem | null> {
  const key = Object.keys(files).find((k) => k.endsWith(`/${id}.json`))
  if (key) return (await files[key]()) as Problem
  const local = readLocal<Record<string, Problem>>(LOCAL_GEN, {})[id]
  if (local) return local
  if (!db) return null
  try {
    const snap = await getDoc(doc(db, 'dsaProblems', id))
    return snap.exists() ? (JSON.parse(snap.data().data as string) as Problem) : null
  } catch {
    return null
  }
}

// ---- AI-generated problems: shared bank (logged in) or this browser ----
const LOCAL_GEN = 'hld.dsa.generated'
const metaOf = (p: Problem): ProblemMeta => ({ id: p.id, title: p.title, topic: p.topic, difficulty: p.difficulty, points: p.points, lc: p.lc, tags: p.tags, order: 0, ai: true })

/** Saves a generated problem; returns where it went */
export async function saveGenerated(p: Problem, uid: string | null): Promise<'shared' | 'local'> {
  const clean = JSON.parse(JSON.stringify(p)) as Problem & { sources?: unknown }
  if (uid && db) {
    try {
      const at = Date.now()
      await setDoc(doc(db, 'dsaProblems', p.id), { data: JSON.stringify(clean), by: uid, at })
      await setDoc(doc(db, 'dsaIndex', p.id), { ...metaOf(p), by: uid, at })
      return 'shared'
    } catch {
      /* already exists or offline: keep it locally */
    }
  }
  writeLocal(LOCAL_GEN, { ...readLocal<Record<string, Problem>>(LOCAL_GEN, {}), [p.id]: clean })
  return 'local'
}

/** Built-in problems + the shared AI bank + this browser's generated ones */
export function useProblemIndex(): ProblemMeta[] {
  const [extra, setExtra] = useState<ProblemMeta[]>(() => Object.values(readLocal<Record<string, Problem>>(LOCAL_GEN, {})).map(metaOf))
  useEffect(() => {
    const local = Object.values(readLocal<Record<string, Problem>>(LOCAL_GEN, {})).map(metaOf)
    if (!db) return setExtra(local)
    getDocs(collection(db, 'dsaIndex'))
      .then((snap) => {
        const shared = snap.docs.map((d) => ({ ...(d.data() as ProblemMeta), id: d.id, ai: true }))
        const ids = new Set(shared.map((m) => m.id))
        setExtra([...shared, ...local.filter((m) => !ids.has(m.id))])
      })
      .catch(() => setExtra(local))
  }, [])
  const builtinLc = new Set(PROBLEMS.map((p) => p.lc).filter(Boolean))
  return [...PROBLEMS, ...extra.filter((m) => !PROBLEMS.some((b) => b.id === m.id) && !(m.lc && builtinLc.has(m.lc)))]
}

const LOCAL = 'hld.dsa.solved'

export function usePractice() {
  const { user } = useStore()
  const [solved, setSolved] = useState<Record<string, Solved>>(() => readLocal(LOCAL, {}))

  useEffect(() => {
    if (!user || !db) {
      setSolved(readLocal(LOCAL, {}))
      return
    }
    const ref = doc(db, 'users', user.uid)
    const local = readLocal<Record<string, Solved>>(LOCAL, {})
    if (Object.keys(local).length) {
      setDoc(ref, { dsa: { solved: local } }, { merge: true })
        .then(() => writeLocal(LOCAL, {}))
        .catch(() => {})
    }
    return onSnapshot(ref, (snap) => setSolved((snap.data()?.dsa?.solved as Record<string, Solved>) ?? {}))
  }, [user])

  const markSolved = useCallback(
    (p: ProblemMeta) => {
      if (solved[p.id]) return false
      const rec = { points: p.points, at: Date.now() }
      setSolved((s) => ({ ...s, [p.id]: rec }))
      if (user && db) setDoc(doc(db, 'users', user.uid), { dsa: { solved: { [p.id]: rec } } }, { merge: true }).catch(() => {})
      else writeLocal(LOCAL, { ...readLocal(LOCAL, {}), [p.id]: rec })
      return true
    },
    [solved, user],
  )

  const points = Object.values(solved).reduce((n, s) => n + s.points, 0)
  return { solved, points, markSolved }
}

// Drafts stay in the browser (they are just scratch code)
export const draftKey = (id: string) => `hld.dsa.code.${id}`
